services:
  frontend:
    build: ./frontend
    container_name: image-cards-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: image-cards-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5001
      - SD_TXT2IMG_URL=http://sd-backend:8000/generate-text-to-image
      - SD_IMG2IMG_URL=http://sd-backend:8000/generate-image-to-image
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - sd-backend

  sd-backend:
    build: ./sd-backend
    container_name: image-cards-sd-backend
    ports:
      - "8000:8000"
    volumes:
      - ~/hf_cache:/root/.cache/huggingface
      - ./sd-backend/outputs:/app/outputs