#!/usr/bin/env python3
"""
Art Detective — unified SD asset generation system.

SHARED STYLE LATENT:
  All backgrounds and objects use BASE_STYLE_PREFIX + BASE_NEGATIVE.
  All assets are generated by SD only — no SVG, no CSS filter correction.

SEED STRATEGY:
  Backgrounds: fixed seed per level (LEVEL_SEEDS).
  Objects:     derived_seed(level_seed, object_id) — deterministic hash.
  Regenerating the same asset always produces the same image.

Usage:
    python generate_scenes.py               # generate everything
    python generate_scenes.py bg forest     # one background
    python generate_scenes.py obj compass   # one object
"""

import sys
import time
import hashlib
import requests
import shutil
import os
import subprocess
import numpy as np
from PIL import Image, ImageDraw, ImageFilter

SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))
OUT_DIR       = os.path.join(SCRIPT_DIR, "../frontend/public/detective")
OBJ_DIR       = os.path.join(OUT_DIR, "objects")
GALLERY_DIR   = os.path.join(SCRIPT_DIR, "../frontend/public/memory-gallery/objects")
GALLERY_BG_DIR = os.path.join(SCRIPT_DIR, "../frontend/public/memory-gallery")
FRONTEND_DIR  = os.path.join(SCRIPT_DIR, "../frontend")
SD_URL        = "http://localhost:8000/generate-text-to-image"

os.makedirs(OUT_DIR,      exist_ok=True)
os.makedirs(OBJ_DIR,      exist_ok=True)
os.makedirs(GALLERY_DIR,  exist_ok=True)
os.makedirs(GALLERY_BG_DIR, exist_ok=True)

# ── Shared style constants ──────────────────────────────────────────────────────
BG_STYLE = "muted cinematic fantasy film background, soft atmospheric lighting, controlled color palette, detailed environment art, subtle magical realism"

OBJ_STYLE = "muted cinematic fantasy prop, soft neutral ambient void, cinematic rim lighting, painterly detail, sharp clean silhouette"

BASE_STYLE_PREFIX = BG_STYLE  # legacy alias — not used in prompts below

BASE_NEGATIVE = (
    "blurry, low quality, watermark, text, "
    "photorealistic, pitch black, horror, "
    "Minecraft, voxel, blocky, low-poly, "
    "cartoon, childish, oversaturated, neon, vivid bright colors, "
    "bright cheerful, colorful fairy tale illustration, storybook cute, "
    "toy-like, plastic, people, characters, faces"
)

OBJ_NEGATIVE = (
    "pure white background, studio product photography, commercial render, "
    "background scene environment landscape, "
    "shadow on plain background, gradient studio backdrop, "
    "multiple objects, Minecraft, voxel, "
    "blurry, watermark, characters, faces"
)

# ── Fixed seeds — one per level, deterministic ─────────────────────────────────
LEVEL_SEEDS = {
    'forest':  1337,
    'village': 137,
    'garden':  256,
    'library': 891,
    'kingdom': 1024,
}


def derived_seed(level_name: str, object_id: str) -> int:
    """Deterministic seed: hash(level_seed + object_id) → int in [0, 2^31)."""
    base = LEVEL_SEEDS.get(level_name, 0)
    h    = hashlib.md5(f"{base}_{object_id}".encode()).hexdigest()
    return int(h[:8], 16) % (2 ** 31)


# ── Background scene specs ──────────────────────────────────────────────────────
BACKGROUNDS = {

    'forest': {
        'filename': 'forest.jpg',
        'seed':     LEVEL_SEEDS['forest'],
        'prompt': BG_STYLE + (
            ", ancient treehouse village in giant mossy tree branches, "
            "rope bridges weathered wood lanterns ferns mushrooms ground fog, "
            "dim amber dusk light deep forest shadow"
        ),
    },

    'village': {
        'filename': 'village.jpg',
        'seed':     LEVEL_SEEDS['village'],
        'prompt': BG_STYLE + (
            ", fairy village cobblestone square curved slate-roof buildings lit windows, "
            "stone fountain market stalls overcast afternoon, "
            "diffused soft light deep street shadows muted greens"
        ),
    },

    'garden': {
        'filename': 'garden.jpg',
        'seed':     LEVEL_SEEDS['garden'],
        'prompt': BG_STYLE + (
            ", overgrown enchanted garden stone path moss stone archway still pond, "
            "hedgerows gazebo twilight atmosphere, "
            "long shadows ground mist desaturated blue-green palette"
        ),
    },

    'library': {
        'filename': 'library.jpg',
        'seed':     LEVEL_SEEDS['library'],
        'prompt': BG_STYLE + (
            ", enchanted library towering curved bookshelves ancient books spiral staircase, "
            "reading alcoves stained glass dust motes dim chandelier, "
            "deep amber shadows aged atmospheric interior"
        ),
    },

    'kingdom': {
        'filename': 'kingdom.jpg',
        'seed':     LEVEL_SEEDS['kingdom'],
        'prompt': BG_STYLE + (
            ", grand royal castle interior hall tall arched stone ceilings, "
            "corridor banners golden chandeliers ornate carved pillars, "
            "polished stone floor warm light soft daylight stained glass windows"
        ),
    },
}

# ── Gallery room backgrounds ────────────────────────────────────────────────────
GALLERY_BACKGROUNDS = {
    'gallery-room': {
        'filename': 'gallery-room.jpg',
        'seed': 7331,
        'prompt': BG_STYLE + (
            ", elegant museum gallery interior dark walls deep indigo plum, "
            "ornate gold picture frames hanging on paneled walls, "
            "polished dark wood parquet floor reflecting warm spotlight glows, "
            "antique display pedestals velvet draped shelves, "
            "coffered ceiling with brass chandeliers dim amber candlelight, "
            "empty gallery room moody atmospheric no people"
        ),
    },
}

# ── Object asset specs ──────────────────────────────────────────────────────────
_OBJ_STYLE = OBJ_STYLE
_OBJ_NEG   = OBJ_NEGATIVE

OBJECTS = {
    # ── Forest: warm amber, aged wood, moss, weathered metal ─────────────────────
    'compass': {
        'filename': 'compass.png',
        'level':    'forest',
        'prompt': "small brass compass open lid engraved rose amber needle, centered floating, warm amber forest rim light, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE + ", cropped, cut off, partial, edge of frame",
    },
    'key': {
        'filename': 'key.png',
        'level':    'forest',
        'prompt': "iron skeleton key trefoil bow emerald gem knotwork engraving weathered metal, moss patina warm amber forest rim light, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    # ── Village: warm golden, craft metal, fabric, cobblestone tones ─────────────
    'lantern': {
        'filename': 'lantern.png',
        'level':    'village',
        'prompt': "brass hanging lantern scrollwork iron frame amber glass panels warm glow inside, village-craft metal warm golden afternoon rim light, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    'potion': {
        'filename': 'potion.png',
        'level':    'village',
        'prompt': "glass potion bottle teal liquid cork stopper purple wax parchment label, apothecary craft warm golden daylight rim light, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    # ── Garden: cool blue-green twilight, worn brass, subtle iridescence ──────────
    'magnifying-glass': {
        'filename': 'magnifying-glass.png',
        'level':    'garden',
        'prompt': "brass magnifying glass oval engraved frame crystal lens rosewood handle, garden-worn patina cool blue-green twilight ambient, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    'butterfly': {
        'filename': 'butterfly.png',
        'level':    'garden',
        'prompt': "butterfly wings spread sage green blue gold vein pattern iridescent, cool twilight garden ambient light delicate natural, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    # ── Library: warm amber candlelight, brass, parchment, leather ───────────────
    'quill': {
        'filename': 'quill.png',
        'level':    'library',
        'prompt': "ivory quill pen full plumage gold nib ink-stained barbs ruffled, warm amber candlelight library rim light parchment tone, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    'pocket-watch': {
        'filename': 'pocket-watch.png',
        'level':    'library',
        'prompt': "open gold pocket watch cream face blue hands clockwork gears chain, warm brass candlelight aged library patina, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    # ── Kingdom: warm sunset gold, engraved stone, castle atmosphere ─────────────
    'star-charm': {
        'filename': 'star-charm.png',
        'level':    'kingdom',
        'prompt': "gold star pendant five points amethyst gems engraved ring loop, warm golden sunset kingdom rim light stone castle atmosphere, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    # ── Kingdom interior: chandelier gold, stone, heraldic materials ──────────────
    'royal-seal': {
        'filename': 'royal-seal.png',
        'level':    'kingdom',
        'prompt': "gold royal wax stamp seal engraved crest coat of arms, warm golden castle chandelier rim light aged metal, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    'banner-charm': {
        'filename': 'banner-charm.png',
        'level':    'kingdom',
        'prompt': "small royal insignia pennant banner charm embroidered heraldic crest, warm castle interior chandelier light fabric silk, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
    'feather-token': {
        'filename': 'feather-token.png',
        'level':    'kingdom',
        'prompt': "engraved metallic feather token charm gold-tipped rune markings, warm castle interior chandelier golden rim light, " + OBJ_STYLE,
        'negative': OBJ_NEGATIVE,
    },
}


# ── Memory Gallery object specs ────────────────────────────────────────────────
# Same pipeline as art-detective objects: SD → buffer → rembg → pad_object (square).
# Seeds are derived from a fixed gallery base (seed 42) + object id.
GALLERY_SEED_BASE = 42

GALLERY_OBJECTS = {
    'portrait':   { 'filename': 'portrait.png',
        'prompt': "gilt baroque wooden picture frame ornate oil painting portrait aged canvas museum display, warm amber spotlight, " + OBJ_STYLE },
    'vase':       { 'filename': 'vase.png',
        'prompt': "ancient greek amphora ceramic blue white painted figures terracotta clay body museum exhibit, cool gallery light, " + OBJ_STYLE },
    'clock':      { 'filename': 'clock.png',
        'prompt': "antique brass mantel clock roman numerals glass dome pendulum ornate scrollwork, warm golden light, " + OBJ_STYLE },
    'fern':       { 'filename': 'fern.png',
        'prompt': "potted maidenhair fern delicate green fronds terracotta clay pot soil, soft natural light, " + OBJ_STYLE },
    'bust':       { 'filename': 'bust.png',
        'prompt': "classical marble bust ancient roman portrait carved stone pedestal museum sculpture, cool diffused gallery light, " + OBJ_STYLE },
    'books':      { 'filename': 'books.png',
        'prompt': "stack ancient leather-bound books gold lettering embossed worn spines aged paper, warm amber candlelight, " + OBJ_STYLE },
    'lantern':    { 'filename': 'lantern.png',
        'prompt': "antique brass oil lantern octagonal glass panels ironwork handle amber flame glow, warm golden light, " + OBJ_STYLE },
    'mask':       { 'filename': 'mask.png',
        'prompt': "venetian carnival masquerade mask gold silver paint feathers gemstones ornate detailed, warm gallery light, " + OBJ_STYLE },
    'orb':        { 'filename': 'orb.png',
        'prompt': "crystal glass sphere orb brass stand etched mystical star patterns, cool blue ambient glow, " + OBJ_STYLE },
    'globe':      { 'filename': 'globe.png',
        'prompt': "antique wooden world globe brass meridian ring aged parchment map oceans stand, warm amber light, " + OBJ_STYLE },
    'owl':        { 'filename': 'owl.png',
        'prompt': "carved stone owl figurine detailed feathers perched base museum specimen, cool stone diffused light, " + OBJ_STYLE },
    'elephant':   { 'filename': 'elephant.png',
        'prompt': "jade carved elephant figurine polished green stone raised trunk detailed tusks display, soft green ambient, " + OBJ_STYLE },
    'mirror':     { 'filename': 'mirror.png',
        'prompt': "ornate baroque gilt oval mirror beveled glass aged gold carved frame museum wall, warm gallery light, " + OBJ_STYLE },
    'hourglass':  { 'filename': 'hourglass.png',
        'prompt': "antique brass hourglass sand flowing glass bulbs ornate metal frame engraved base, warm golden light, " + OBJ_STYLE },
    'crown':      { 'filename': 'crown.png',
        'prompt': "gold jeweled crown rubies emeralds sapphires ornate velvet cushion royal display, warm regal light, " + OBJ_STYLE },
    'violin':     { 'filename': 'violin.png',
        'prompt': "classical wooden violin varnished spruce maple F-holes strings bridge bow aged, warm amber light, " + OBJ_STYLE },
    'amulet':     { 'filename': 'amulet.png',
        'prompt': "round blue glass evil eye nazar amulet gold wire wrapped pendant cord, warm gallery light, " + OBJ_STYLE },
    'moondial':   { 'filename': 'moondial.png',
        'prompt': "celestial bronze moon dial crescent astronomical instrument engraved stand, cool moonlit ambient glow, " + OBJ_STYLE },
    'flask':      { 'filename': 'flask.png',
        'prompt': "alchemist glass flask green glowing liquid cork stopper brass ring stand mystical, cool mystical glow, " + OBJ_STYLE },
    'fossil':     { 'filename': 'fossil.png',
        'prompt': "spiral ammonite fossil grey limestone museum specimen geological chambers detailed, cool stone light, " + OBJ_STYLE },
}
# All gallery objects share the same negative prompt
for _v in GALLERY_OBJECTS.values():
    _v['negative'] = OBJ_NEGATIVE


# ── Background removal ──────────────────────────────────────────────────────────
def remove_background(pil_img: Image.Image, **_) -> Image.Image:
    """Neural background removal via rembg — handles gradients and soft edges."""
    from rembg import remove as rembg_remove
    return rembg_remove(pil_img.convert('RGBA'))


def pad_object(rgba: Image.Image, pad_fraction: float = 0.12) -> Image.Image:
    """
    Crop to the non-transparent bounding box, add uniform padding, then make
    the canvas square by centering the object in a square of side = max(w, h).
    Square canvas is required because the game renders objects into a square
    item.w × item.h box — non-square canvases cause non-uniform stretch.
    """
    bbox = rgba.getbbox()
    if not bbox:
        return rgba
    cropped = rgba.crop(bbox)
    cw, ch = cropped.size
    pad = max(int(max(cw, ch) * pad_fraction), 8)
    inner_w = cw + pad * 2
    inner_h = ch + pad * 2
    side = max(inner_w, inner_h)          # force square
    off_x = (side - inner_w) // 2
    off_y = (side - inner_h) // 2
    out = Image.new('RGBA', (side, side), (0, 0, 0, 0))
    out.paste(cropped, (pad + off_x, pad + off_y))
    return out


# ── SD call ─────────────────────────────────────────────────────────────────────
def call_sd(prompt: str, negative: str, seed: int,
            width: int = 512, height: int = 512,
            upscale: int = 1) -> str:
    """
    POST to the SD backend, return the local path of the saved output file.
    Raises on connection error or non-2xx response.
    """
    payload = {
        "prompt":          prompt,
        "negative_prompt": negative,
        "width":           width,
        "height":          height,
        "steps":           40,
        "cfg_scale":       7.0,
        "sampler":         "DPM++ 2M Karras",
        "upscale_factor":  upscale,
        "seed":            seed,
    }
    last_err = None
    for attempt in range(1, 4):
        try:
            r = requests.post(SD_URL, json=payload, timeout=900)
            if r.status_code == 500:
                last_err = f"500 Server Error (attempt {attempt}/3)"
                print(f"  ! SD returned 500 — waiting 25s before retry…")
                time.sleep(25)
                continue
            r.raise_for_status()
            last_err = None
            break
        except requests.exceptions.ConnectionError:
            raise RuntimeError(
                f"SD backend not reachable at {SD_URL}\n"
                "  Start it: cd sd-backend && uvicorn app:app --reload --port 8000"
            )
        except requests.exceptions.ReadTimeout:
            raise RuntimeError(
                f"SD backend timed out after 900s — model may have crashed. "
                "Check uvicorn logs and restart if needed."
            )
    if last_err:
        raise RuntimeError(f"SD backend failed after 3 attempts: {last_err}")
    data = r.json()
    return os.path.join(SCRIPT_DIR, "outputs", data["filename"])


# ── Generators ──────────────────────────────────────────────────────────────────
def generate_background(name: str, force: bool = False) -> None:
    spec = BACKGROUNDS[name]
    dst  = os.path.join(OUT_DIR, spec['filename'])
    if not force and os.path.exists(dst):
        print(f"\n[bg:{name}]  skipped (already exists — use --force to overwrite)")
        return
    print(f"\n[bg:{name}]  seed={spec['seed']}")
    t0 = time.time()
    src = call_sd(
        spec['prompt'], spec.get('negative', BASE_NEGATIVE),
        seed=spec['seed'],
        width=768, height=512, upscale=2,   # → 1536×1024 matches staticSceneData imageW/imageH
    )
    dst = os.path.join(OUT_DIR, spec['filename'])
    shutil.copy2(src, dst)
    kb = os.path.getsize(dst) // 1024
    print(f"  ✓ {dst}  ({kb} KB)  [{time.time()-t0:.0f}s]")


def generate_gallery_background(name: str, force: bool = False) -> None:
    spec = GALLERY_BACKGROUNDS[name]
    dst  = os.path.join(GALLERY_BG_DIR, spec['filename'])
    if not force and os.path.exists(dst):
        print(f"\n[gallery-bg:{name}]  skipped (already exists — use --force to overwrite)")
        return
    print(f"\n[gallery-bg:{name}]  seed={spec['seed']}")
    t0 = time.time()
    src = call_sd(
        spec['prompt'], spec.get('negative', BASE_NEGATIVE),
        seed=spec['seed'],
        width=768, height=512, upscale=2,
    )
    shutil.copy2(src, dst)
    kb = os.path.getsize(dst) // 1024
    print(f"  ✓ {dst}  ({kb} KB)  [{time.time()-t0:.0f}s]")


def generate_object(name: str, force: bool = False) -> None:
    spec  = OBJECTS[name]
    dst   = os.path.join(OBJ_DIR, spec['filename'])
    if not force and os.path.exists(dst):
        print(f"\n[obj:{name}]  skipped (already exists — use --force to overwrite)")
        return
    seed  = derived_seed(spec['level'], name)
    print(f"\n[obj:{name}]  level={spec['level']}  seed={seed}")
    t0 = time.time()
    src_path = call_sd(
        spec['prompt'], spec['negative'],
        seed=seed,
        width=512, height=512, upscale=1,
    )
    raw     = Image.open(src_path).convert('RGB')
    # Add neutral buffer around SD output before rembg so the object is never
    # at the canvas edge when the model computes its alpha mask — avoids the
    # hard-cut antialiasing artifact at the circular rim.
    buf_px  = 48
    buffered = Image.new('RGB', (raw.width + buf_px*2, raw.height + buf_px*2), (230, 225, 215))
    buffered.paste(raw, (buf_px, buf_px))
    rgba    = remove_background(buffered)
    rgba    = pad_object(rgba)          # crop tight + square canvas with uniform margin
    dst     = os.path.join(OBJ_DIR, spec['filename'])
    rgba.save(dst, 'PNG', optimize=True)
    kb = os.path.getsize(dst) // 1024
    print(f"  ✓ {dst}  ({kb} KB)  [{time.time()-t0:.0f}s]")


def generate_gallery_object(name: str, force: bool = False) -> None:
    spec = GALLERY_OBJECTS[name]
    dst  = os.path.join(GALLERY_DIR, spec['filename'])
    if not force and os.path.exists(dst):
        print(f"\n[gallery:{name}]  skipped (already exists — use --force to overwrite)")
        return
    seed = derived_seed('gallery', name)
    print(f"\n[gallery:{name}]  seed={seed}")
    t0 = time.time()
    src_path = call_sd(spec['prompt'], spec['negative'], seed=seed, width=512, height=512, upscale=2)
    raw      = Image.open(src_path).convert('RGB')
    buf_px   = 48
    buffered = Image.new('RGB', (raw.width + buf_px*2, raw.height + buf_px*2), (230, 225, 215))
    buffered.paste(raw, (buf_px, buf_px))
    rgba     = remove_background(buffered)
    rgba     = pad_object(rgba)
    rgba.save(dst, 'PNG', optimize=True)
    kb = os.path.getsize(dst) // 1024
    print(f"  ✓ {dst}  ({kb} KB)  [{time.time()-t0:.0f}s]")


# ── Post-generation rebuild ──────────────────────────────────────────────────────
def rebuild_frontend() -> None:
    print(f"\n[build] Rebuilding frontend…")
    result = subprocess.run(
        ["npm", "run", "build"],
        cwd=FRONTEND_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        print("[build] ✓ dist updated")
    else:
        print(f"[build] ✗ failed (exit {result.returncode}):")
        print(result.stderr[-1500:])
        print("  Manual fix: cd frontend && npm run build")


# ── Entry point ──────────────────────────────────────────────────────────────────
def main() -> None:
    args  = sys.argv[1:]
    force = '--force' in args
    args  = [a for a in args if a != '--force']

    if args and args[0] == 'bg':
        name = args[1] if len(args) > 1 else None
        if name and name not in BACKGROUNDS:
            print(f"Unknown background '{name}'. Available: {', '.join(BACKGROUNDS)}")
            sys.exit(1)
        targets = [name] if name else list(BACKGROUNDS)
        for n in targets:
            generate_background(n, force=force)

    elif args and args[0] == 'obj':
        name = args[1] if len(args) > 1 else None
        if name and name not in OBJECTS:
            print(f"Unknown object '{name}'. Available: {', '.join(OBJECTS)}")
            sys.exit(1)
        targets = [name] if name else list(OBJECTS)
        for n in targets:
            generate_object(n, force=force)

    elif args and args[0] == 'gallery':
        name = args[1] if len(args) > 1 else None
        if name and name not in GALLERY_OBJECTS:
            print(f"Unknown gallery object '{name}'. Available: {', '.join(GALLERY_OBJECTS)}")
            sys.exit(1)
        targets = [name] if name else list(GALLERY_OBJECTS)
        for n in targets:
            generate_gallery_object(n, force=force)

    elif args and args[0] == 'gallery-bg':
        name = args[1] if len(args) > 1 else None
        if name and name not in GALLERY_BACKGROUNDS:
            print(f"Unknown gallery background '{name}'. Available: {', '.join(GALLERY_BACKGROUNDS)}")
            sys.exit(1)
        targets = [name] if name else list(GALLERY_BACKGROUNDS)
        for n in targets:
            generate_gallery_background(n, force=force)

    else:
        # No subcommand — generate everything, skipping existing files
        print("Generating all backgrounds…")
        for name in BACKGROUNDS:
            generate_background(name, force=force)
        print("\nGenerating all objects…")
        for name in OBJECTS:
            generate_object(name, force=force)

    rebuild_frontend()
    print("\nDone. Refresh browser to see new assets.")


if __name__ == "__main__":
    main()
