services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: ic-fineart-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: image-cards-backend
    ports:
      - "5001:5001"
    env_file:
      - ../backend/.env
    depends_on:
      - qwen-local
      - sd-backend
    restart: unless-stopped

  qwen-local:
    build:
      context: ../qwen-backend
      dockerfile: Dockerfile
    container_name: image-cards-qwen-local
    ports:
      - "8001:8001"
    env_file:
      - ../qwen-backend/.env
    environment:
      - QWEN_MODEL=Qwen/Qwen2.5-1.5B-Instruct
    volumes:
      - ~/hf_cache:/root/.cache/huggingface
    restart: unless-stopped

  sd-backend:
    build:
      context: ../sd-backend
      dockerfile: Dockerfile
    container_name: ic-fineart-sd-backend
    ports:
      - "8000:8000"
    env_file:
      - ../sd-backend/.env
    volumes:
      - ~/hf_cache:/root/.cache/huggingface
      - ../sd-backend/outputs:/app/outputs
    restart: unless-stopped