import fs   from 'fs';
import path from 'path';
import { Request, Response, NextFunction } from 'express';
import { generateDetectiveScene, SCENE_SPECS } from '../services/detectiveService.js';
import { tilePath, manifestPath, PUBLIC_DIR }  from '../services/tileService.js';

const DETECTIVE_DIR = path.join(PUBLIC_DIR, 'detective');

/** POST /api/art-detective/generate-scene  body: { levelNum } */
export async function generateSceneController(
  req: Request, res: Response, next: NextFunction,
): Promise<void> {
  try {
    const levelNum = Number(req.body.levelNum);
    if (!levelNum || levelNum < 1 || levelNum > SCENE_SPECS.length) {
      res.status(400).json({ success: false, error: 'Invalid levelNum' });
      return;
    }
    const scene = await generateDetectiveScene(levelNum);
    res.json({ success: true, data: scene });
  } catch (err) {
    next(err);
  }
}

/** GET /api/art-detective/scene-image/:sceneId
 *  Serves the full-resolution scene image generated by SD.
 */
export function getSceneImageController(req: Request, res: Response): void {
  const { sceneId } = req.params;

  // Sanitise — only allow safe directory names
  if (!/^[\w-]+$/.test(sceneId)) {
    res.status(400).end();
    return;
  }

  const fp = path.join(DETECTIVE_DIR, sceneId, 'full.jpg');
  if (!fs.existsSync(fp)) {
    res.status(404).json({ error: 'Scene image not found' });
    return;
  }

  res.setHeader('Cache-Control', 'public, max-age=3600');
  res.setHeader('Content-Type',  'image/jpeg');
  res.sendFile(fp, { root: '/' });
}

/** GET /api/art-detective/tiles/:sceneId/:z/:tx/:ty */
export function getTileController(req: Request, res: Response): void {
  const { sceneId, z, tx, ty } = req.params;
  const fp = tilePath(sceneId, Number(z), Number(tx), Number(ty));

  if (!fs.existsSync(fp)) {
    res.status(404).end();
    return;
  }
  res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
  res.setHeader('Content-Type',  'image/jpeg');
  res.sendFile(fp, { root: '/' });
}

/** GET /api/art-detective/manifest/:sceneId */
export function getManifestController(req: Request, res: Response): void {
  const fp = manifestPath(req.params.sceneId);
  if (!fs.existsSync(fp)) {
    res.status(404).json({ error: 'Manifest not found' });
    return;
  }
  res.json(JSON.parse(fs.readFileSync(fp, 'utf-8')));
}

/** GET /api/art-detective/objects/:sceneId */
export function getObjectsController(req: Request, res: Response): void {
  const fp = path.join(DETECTIVE_DIR, req.params.sceneId, 'objects.json');
  if (!fs.existsSync(fp)) {
    res.json({ success: true, data: { hiddenObjects: [] } });
    return;
  }
  res.json({ success: true, data: JSON.parse(fs.readFileSync(fp, 'utf-8')) });
}
