import { ART_STYLES } from '../../systems/artStyles';

export interface MemoryCard {
  id: number;
  symbolId: string;
  artStyleId: string;
  emoji: string;
  name: string;
}

export interface LevelConfig {
  cardCount: number;
  roundCount: number;
  cols: number;
  blankMs: number;
}

export const LEVEL_CONFIGS: LevelConfig[] = [
  { cardCount:  20, roundCount: 4, cols:  5, blankMs:  2000 },
  { cardCount:  30, roundCount: 4, cols:  6, blankMs:  3000 },
  { cardCount:  42, roundCount: 5, cols:  7, blankMs:  4000 },
  { cardCount:  56, roundCount: 5, cols:  8, blankMs:  5000 },
  { cardCount:  72, roundCount: 5, cols:  9, blankMs:  6000 },
  { cardCount:  90, roundCount: 4, cols: 10, blankMs:  7000 },
  { cardCount: 110, roundCount: 4, cols: 11, blankMs:  8000 },
  { cardCount: 132, roundCount: 4, cols: 12, blankMs: 10000 },
  { cardCount: 156, roundCount: 3, cols: 13, blankMs: 12000 },
  { cardCount: 182, roundCount: 3, cols: 14, blankMs: 14000 },
  { cardCount: 225, roundCount: 3, cols: 15, blankMs: 16000 },
];

export const MEMORY_POOL = [
  // Domestic animals
  { symbolId: 'dog',         emoji: '🐶', name: 'Dog' },
  { symbolId: 'cat',         emoji: '🐱', name: 'Cat' },
  { symbolId: 'rabbit',      emoji: '🐰', name: 'Rabbit' },
  { symbolId: 'hamster',     emoji: '🐹', name: 'Hamster' },
  { symbolId: 'mouse',       emoji: '🐭', name: 'Mouse' },
  // Wild mammals
  { symbolId: 'lion',        emoji: '🦁', name: 'Lion' },
  { symbolId: 'tiger',       emoji: '🐯', name: 'Tiger' },
  { symbolId: 'bear',        emoji: '🐻', name: 'Bear' },
  { symbolId: 'panda',       emoji: '🐼', name: 'Panda' },
  { symbolId: 'fox',         emoji: '🦊', name: 'Fox' },
  { symbolId: 'wolf',        emoji: '🐺', name: 'Wolf' },
  { symbolId: 'koala',       emoji: '🐨', name: 'Koala' },
  { symbolId: 'monkey',      emoji: '🐵', name: 'Monkey' },
  { symbolId: 'gorilla',     emoji: '🦍', name: 'Gorilla' },
  { symbolId: 'elephant',    emoji: '🐘', name: 'Elephant' },
  { symbolId: 'giraffe',     emoji: '🦒', name: 'Giraffe' },
  { symbolId: 'zebra',       emoji: '🦓', name: 'Zebra' },
  { symbolId: 'rhino',       emoji: '🦏', name: 'Rhino' },
  { symbolId: 'hippo',       emoji: '🦛', name: 'Hippo' },
  { symbolId: 'camel',       emoji: '🐪', name: 'Camel' },
  { symbolId: 'kangaroo',    emoji: '🦘', name: 'Kangaroo' },
  { symbolId: 'deer',        emoji: '🦌', name: 'Deer' },
  { symbolId: 'horse',       emoji: '🐴', name: 'Horse' },
  { symbolId: 'unicorn',     emoji: '🦄', name: 'Unicorn' },
  { symbolId: 'pig',         emoji: '🐷', name: 'Pig' },
  { symbolId: 'cow',         emoji: '🐮', name: 'Cow' },
  { symbolId: 'sheep',       emoji: '🐑', name: 'Sheep' },
  { symbolId: 'goat',        emoji: '🐐', name: 'Goat' },
  { symbolId: 'llama',       emoji: '🦙', name: 'Llama' },
  { symbolId: 'buffalo',     emoji: '🦬', name: 'Buffalo' },
  // Birds
  { symbolId: 'chicken',     emoji: '🐔', name: 'Chicken' },
  { symbolId: 'penguin',     emoji: '🐧', name: 'Penguin' },
  { symbolId: 'chick',       emoji: '🐤', name: 'Chick' },
  { symbolId: 'duck',        emoji: '🦆', name: 'Duck' },
  { symbolId: 'eagle',       emoji: '🦅', name: 'Eagle' },
  { symbolId: 'owl',         emoji: '🦉', name: 'Owl' },
  { symbolId: 'parrot',      emoji: '🦜', name: 'Parrot' },
  { symbolId: 'flamingo',    emoji: '🦩', name: 'Flamingo' },
  { symbolId: 'peacock',     emoji: '🦚', name: 'Peacock' },
  { symbolId: 'swan',        emoji: '🦢', name: 'Swan' },
  { symbolId: 'turkey',      emoji: '🦃', name: 'Turkey' },
  { symbolId: 'bat',         emoji: '🦇', name: 'Bat' },
  { symbolId: 'dove',        emoji: '🕊', name: 'Dove' },
  // Ocean
  { symbolId: 'whale',       emoji: '🐋', name: 'Whale' },
  { symbolId: 'dolphin',     emoji: '🐬', name: 'Dolphin' },
  { symbolId: 'shark',       emoji: '🦈', name: 'Shark' },
  { symbolId: 'octopus',     emoji: '🐙', name: 'Octopus' },
  { symbolId: 'crab',        emoji: '🦀', name: 'Crab' },
  { symbolId: 'lobster',     emoji: '🦞', name: 'Lobster' },
  { symbolId: 'shrimp',      emoji: '🦐', name: 'Shrimp' },
  { symbolId: 'squid',       emoji: '🦑', name: 'Squid' },
  { symbolId: 'turtle',      emoji: '🐢', name: 'Turtle' },
  { symbolId: 'seal',        emoji: '🦭', name: 'Seal' },
  { symbolId: 'fish',        emoji: '🐟', name: 'Fish' },
  { symbolId: 'blowfish',    emoji: '🐡', name: 'Blowfish' },
  { symbolId: 'tropfish',    emoji: '🐠', name: 'Tropical Fish' },
  // Reptiles & insects
  { symbolId: 'snake',       emoji: '🐍', name: 'Snake' },
  { symbolId: 'lizard',      emoji: '🦎', name: 'Lizard' },
  { symbolId: 'frog',        emoji: '🐸', name: 'Frog' },
  { symbolId: 'butterfly',   emoji: '🦋', name: 'Butterfly' },
  { symbolId: 'bee',         emoji: '🐝', name: 'Bee' },
  { symbolId: 'ladybug',     emoji: '🐞', name: 'Ladybug' },
  { symbolId: 'ant',         emoji: '🐜', name: 'Ant' },
  { symbolId: 'snail',       emoji: '🐌', name: 'Snail' },
  { symbolId: 'spider',      emoji: '🕷', name: 'Spider' },
  { symbolId: 'scorpion',    emoji: '🦂', name: 'Scorpion' },
  { symbolId: 'cricket',     emoji: '🦗', name: 'Cricket' },
  { symbolId: 'mosquito',    emoji: '🦟', name: 'Mosquito' },
  { symbolId: 'worm',        emoji: '🪱', name: 'Worm' },
  { symbolId: 'caterpillar', emoji: '🐛', name: 'Caterpillar' },
  // Fruit
  { symbolId: 'apple',       emoji: '🍎', name: 'Apple' },
  { symbolId: 'pear',        emoji: '🍐', name: 'Pear' },
  { symbolId: 'orange',      emoji: '🍊', name: 'Orange' },
  { symbolId: 'lemon',       emoji: '🍋', name: 'Lemon' },
  { symbolId: 'banana',      emoji: '🍌', name: 'Banana' },
  { symbolId: 'watermelon',  emoji: '🍉', name: 'Watermelon' },
  { symbolId: 'grapes',      emoji: '🍇', name: 'Grapes' },
  { symbolId: 'strawberry',  emoji: '🍓', name: 'Strawberry' },
  { symbolId: 'cherry',      emoji: '🍒', name: 'Cherry' },
  { symbolId: 'peach',       emoji: '🍑', name: 'Peach' },
  { symbolId: 'mango',       emoji: '🥭', name: 'Mango' },
  { symbolId: 'pineapple',   emoji: '🍍', name: 'Pineapple' },
  { symbolId: 'coconut',     emoji: '🥥', name: 'Coconut' },
  { symbolId: 'kiwi',        emoji: '🥝', name: 'Kiwi' },
  { symbolId: 'avocado',     emoji: '🥑', name: 'Avocado' },
  { symbolId: 'tomato',      emoji: '🍅', name: 'Tomato' },
  { symbolId: 'blueberries', emoji: '🫐', name: 'Blueberries' },
  { symbolId: 'melon',       emoji: '🍈', name: 'Melon' },
  // Vegetables
  { symbolId: 'eggplant',    emoji: '🍆', name: 'Eggplant' },
  { symbolId: 'broccoli',    emoji: '🥦', name: 'Broccoli' },
  { symbolId: 'carrot',      emoji: '🥕', name: 'Carrot' },
  { symbolId: 'corn',        emoji: '🌽', name: 'Corn' },
  { symbolId: 'pepper',      emoji: '🌶', name: 'Pepper' },
  { symbolId: 'potato',      emoji: '🥔', name: 'Potato' },
  { symbolId: 'garlic',      emoji: '🧄', name: 'Garlic' },
  { symbolId: 'onion',       emoji: '🧅', name: 'Onion' },
  { symbolId: 'cucumber',    emoji: '🥒', name: 'Cucumber' },
  { symbolId: 'lettuce',     emoji: '🥬', name: 'Lettuce' },
  { symbolId: 'mushroom',    emoji: '🍄', name: 'Mushroom' },
  { symbolId: 'peanuts',     emoji: '🥜', name: 'Peanuts' },
  { symbolId: 'chestnut',    emoji: '🌰', name: 'Chestnut' },
  // Cooked food
  { symbolId: 'pizza',       emoji: '🍕', name: 'Pizza' },
  { symbolId: 'burger',      emoji: '🍔', name: 'Burger' },
  { symbolId: 'fries',       emoji: '🍟', name: 'Fries' },
  { symbolId: 'hotdog',      emoji: '🌭', name: 'Hot Dog' },
  { symbolId: 'taco',        emoji: '🌮', name: 'Taco' },
  { symbolId: 'burrito',     emoji: '🌯', name: 'Burrito' },
  { symbolId: 'sushi',       emoji: '🍣', name: 'Sushi' },
  { symbolId: 'ramen',       emoji: '🍜', name: 'Ramen' },
  { symbolId: 'spaghetti',   emoji: '🍝', name: 'Spaghetti' },
  { symbolId: 'rice',        emoji: '🍚', name: 'Rice' },
  { symbolId: 'bread',       emoji: '🍞', name: 'Bread' },
  { symbolId: 'croissant',   emoji: '🥐', name: 'Croissant' },
  { symbolId: 'pancakes',    emoji: '🥞', name: 'Pancakes' },
  { symbolId: 'waffle',      emoji: '🧇', name: 'Waffle' },
  { symbolId: 'egg',         emoji: '🥚', name: 'Egg' },
  { symbolId: 'cheese',      emoji: '🧀', name: 'Cheese' },
  { symbolId: 'bacon',       emoji: '🥓', name: 'Bacon' },
  { symbolId: 'chicken-leg', emoji: '🍗', name: 'Chicken Leg' },
  { symbolId: 'steak',       emoji: '🥩', name: 'Steak' },
  { symbolId: 'curry',       emoji: '🍛', name: 'Curry' },
  { symbolId: 'soup',        emoji: '🍲', name: 'Soup' },
  { symbolId: 'bento',       emoji: '🍱', name: 'Bento' },
  // Sweets
  { symbolId: 'cake',        emoji: '🎂', name: 'Cake' },
  { symbolId: 'cupcake',     emoji: '🧁', name: 'Cupcake' },
  { symbolId: 'donut',       emoji: '🍩', name: 'Donut' },
  { symbolId: 'cookie',      emoji: '🍪', name: 'Cookie' },
  { symbolId: 'chocolate',   emoji: '🍫', name: 'Chocolate' },
  { symbolId: 'candy',       emoji: '🍬', name: 'Candy' },
  { symbolId: 'lollipop',    emoji: '🍭', name: 'Lollipop' },
  { symbolId: 'popcorn',     emoji: '🍿', name: 'Popcorn' },
  { symbolId: 'icecream',    emoji: '🍦', name: 'Ice Cream' },
  { symbolId: 'shavedice',   emoji: '🍧', name: 'Shaved Ice' },
  { symbolId: 'honey',       emoji: '🍯', name: 'Honey' },
  { symbolId: 'pie',         emoji: '🥧', name: 'Pie' },
  // Drinks
  { symbolId: 'coffee',      emoji: '☕', name: 'Coffee' },
  { symbolId: 'tea',         emoji: '🍵', name: 'Tea' },
  { symbolId: 'juice',       emoji: '🧃', name: 'Juice' },
  { symbolId: 'milk',        emoji: '🥛', name: 'Milk' },
  { symbolId: 'boba',        emoji: '🧋', name: 'Boba Tea' },
  { symbolId: 'soda',        emoji: '🥤', name: 'Soda' },
  { symbolId: 'cocktail',    emoji: '🍹', name: 'Cocktail' },
  // Flowers
  { symbolId: 'rose',        emoji: '🌹', name: 'Rose' },
  { symbolId: 'sunflower',   emoji: '🌻', name: 'Sunflower' },
  { symbolId: 'blossom',     emoji: '🌸', name: 'Blossom' },
  { symbolId: 'tulip',       emoji: '🌷', name: 'Tulip' },
  { symbolId: 'hibiscus',    emoji: '🌺', name: 'Hibiscus' },
  { symbolId: 'bouquet',     emoji: '💐', name: 'Bouquet' },
  { symbolId: 'flower',      emoji: '🌼', name: 'Flower' },
  // Plants / nature
  { symbolId: 'seedling',    emoji: '🌱', name: 'Seedling' },
  { symbolId: 'cactus',      emoji: '🌵', name: 'Cactus' },
  { symbolId: 'tree',        emoji: '🌳', name: 'Tree' },
  { symbolId: 'palm',        emoji: '🌴', name: 'Palm Tree' },
  { symbolId: 'pine',        emoji: '🌲', name: 'Pine Tree' },
  { symbolId: 'leaf',        emoji: '🍃', name: 'Leaf' },
  { symbolId: 'maple',       emoji: '🍁', name: 'Maple Leaf' },
  { symbolId: 'fallenleaf',  emoji: '🍂', name: 'Fallen Leaf' },
  { symbolId: 'herb',        emoji: '🌿', name: 'Herb' },
  { symbolId: 'clover',      emoji: '🍀', name: 'Clover' },
  { symbolId: 'bamboo',      emoji: '🎋', name: 'Bamboo' },
  { symbolId: 'sheaf',       emoji: '🌾', name: 'Sheaf' },
  // Weather / sky
  { symbolId: 'sun',         emoji: '☀️', name: 'Sun' },
  { symbolId: 'moon',        emoji: '🌙', name: 'Moon' },
  { symbolId: 'star',        emoji: '⭐', name: 'Star' },
  { symbolId: 'glowstar',    emoji: '🌟', name: 'Glowing Star' },
  { symbolId: 'shootstar',   emoji: '🌠', name: 'Shooting Star' },
  { symbolId: 'cloud',       emoji: '☁️', name: 'Cloud' },
  { symbolId: 'rainbow',     emoji: '🌈', name: 'Rainbow' },
  { symbolId: 'lightning',   emoji: '⚡', name: 'Lightning' },
  { symbolId: 'snowflake',   emoji: '❄️', name: 'Snowflake' },
  { symbolId: 'fire',        emoji: '🔥', name: 'Fire' },
  { symbolId: 'waterdrop',   emoji: '💧', name: 'Water Drop' },
  { symbolId: 'wave',        emoji: '🌊', name: 'Wave' },
  { symbolId: 'tornado',     emoji: '🌪', name: 'Tornado' },
  { symbolId: 'snowman',     emoji: '⛄', name: 'Snowman' },
  { symbolId: 'umbrella',    emoji: '☂️', name: 'Umbrella' },
  // Space
  { symbolId: 'rocket',      emoji: '🚀', name: 'Rocket' },
  { symbolId: 'planet',      emoji: '🪐', name: 'Planet' },
  { symbolId: 'ufo',         emoji: '🛸', name: 'UFO' },
  { symbolId: 'alien',       emoji: '👽', name: 'Alien' },
  { symbolId: 'comet',       emoji: '☄️', name: 'Comet' },
  { symbolId: 'satellite',   emoji: '🛰', name: 'Satellite' },
  { symbolId: 'telescope',   emoji: '🔭', name: 'Telescope' },
  // Sports
  { symbolId: 'soccer',      emoji: '⚽', name: 'Soccer' },
  { symbolId: 'basketball',  emoji: '🏀', name: 'Basketball' },
  { symbolId: 'football',    emoji: '🏈', name: 'Football' },
  { symbolId: 'baseball',    emoji: '⚾', name: 'Baseball' },
  { symbolId: 'tennis',      emoji: '🎾', name: 'Tennis' },
  { symbolId: 'volleyball',  emoji: '🏐', name: 'Volleyball' },
  { symbolId: 'rugby',       emoji: '🏉', name: 'Rugby' },
  { symbolId: 'poolball',    emoji: '🎱', name: 'Pool' },
  { symbolId: 'pingpong',    emoji: '🏓', name: 'Ping Pong' },
  { symbolId: 'badminton',   emoji: '🏸', name: 'Badminton' },
  { symbolId: 'boxing',      emoji: '🥊', name: 'Boxing' },
  { symbolId: 'golf',        emoji: '⛳', name: 'Golf' },
  { symbolId: 'skiing',      emoji: '⛷', name: 'Skiing' },
  { symbolId: 'surfing',     emoji: '🏄', name: 'Surfing' },
  { symbolId: 'bowling',     emoji: '🎳', name: 'Bowling' },
  { symbolId: 'archery',     emoji: '🎯', name: 'Archery' },
  { symbolId: 'fishing',     emoji: '🎣', name: 'Fishing' },
  { symbolId: 'climbing',    emoji: '🧗', name: 'Climbing' },
  { symbolId: 'cycling',     emoji: '🚴', name: 'Cycling' },
  { symbolId: 'swimming',    emoji: '🏊', name: 'Swimming' },
  // Vehicles
  { symbolId: 'car',         emoji: '🚗', name: 'Car' },
  { symbolId: 'bus',         emoji: '🚌', name: 'Bus' },
  { symbolId: 'train',       emoji: '🚂', name: 'Train' },
  { symbolId: 'airplane',    emoji: '✈️', name: 'Airplane' },
  { symbolId: 'helicopter',  emoji: '🚁', name: 'Helicopter' },
  { symbolId: 'sailboat',    emoji: '⛵', name: 'Sailboat' },
  { symbolId: 'bicycle',     emoji: '🚲', name: 'Bicycle' },
  { symbolId: 'motorcycle',  emoji: '🏍', name: 'Motorcycle' },
  { symbolId: 'truck',       emoji: '🚚', name: 'Truck' },
  { symbolId: 'ambulance',   emoji: '🚑', name: 'Ambulance' },
  { symbolId: 'firetruck',   emoji: '🚒', name: 'Fire Truck' },
  { symbolId: 'taxi',        emoji: '🚕', name: 'Taxi' },
  { symbolId: 'tractor',     emoji: '🚜', name: 'Tractor' },
  { symbolId: 'scooter',     emoji: '🛵', name: 'Scooter' },
  // Music
  { symbolId: 'guitar',      emoji: '🎸', name: 'Guitar' },
  { symbolId: 'piano',       emoji: '🎹', name: 'Piano' },
  { symbolId: 'violin',      emoji: '🎻', name: 'Violin' },
  { symbolId: 'trumpet',     emoji: '🎺', name: 'Trumpet' },
  { symbolId: 'drum',        emoji: '🥁', name: 'Drum' },
  { symbolId: 'headphones',  emoji: '🎧', name: 'Headphones' },
  { symbolId: 'microphone',  emoji: '🎤', name: 'Microphone' },
  { symbolId: 'musicnote',   emoji: '🎵', name: 'Music Note' },
  { symbolId: 'saxophone',   emoji: '🎷', name: 'Saxophone' },
  // Objects / tools
  { symbolId: 'camera',      emoji: '📷', name: 'Camera' },
  { symbolId: 'phone',       emoji: '📱', name: 'Phone' },
  { symbolId: 'laptop',      emoji: '💻', name: 'Laptop' },
  { symbolId: 'tv',          emoji: '📺', name: 'TV' },
  { symbolId: 'books',       emoji: '📚', name: 'Books' },
  { symbolId: 'pencil',      emoji: '✏️', name: 'Pencil' },
  { symbolId: 'paintbrush',  emoji: '🖌️', name: 'Paintbrush' },
  { symbolId: 'scissors',    emoji: '✂️', name: 'Scissors' },
  { symbolId: 'hammer',      emoji: '🔨', name: 'Hammer' },
  { symbolId: 'wrench',      emoji: '🔧', name: 'Wrench' },
  { symbolId: 'magnifier',   emoji: '🔍', name: 'Magnifier' },
  { symbolId: 'key',         emoji: '🔑', name: 'Key' },
  { symbolId: 'lock',        emoji: '🔒', name: 'Lock' },
  { symbolId: 'lightbulb',   emoji: '💡', name: 'Light Bulb' },
  { symbolId: 'compass',     emoji: '🧭', name: 'Compass' },
  { symbolId: 'map',         emoji: '🗺', name: 'Map' },
  { symbolId: 'backpack',    emoji: '🎒', name: 'Backpack' },
  { symbolId: 'glasses',     emoji: '👓', name: 'Glasses' },
  { symbolId: 'watch',       emoji: '⌚', name: 'Watch' },
  { symbolId: 'microscope',  emoji: '🔬', name: 'Microscope' },
  // Celebrations
  { symbolId: 'crown',       emoji: '👑', name: 'Crown' },
  { symbolId: 'gem',         emoji: '💎', name: 'Gem' },
  { symbolId: 'trophy',      emoji: '🏆', name: 'Trophy' },
  { symbolId: 'medal',       emoji: '🥇', name: 'Medal' },
  { symbolId: 'gift',        emoji: '🎁', name: 'Gift' },
  { symbolId: 'balloon',     emoji: '🎈', name: 'Balloon' },
  { symbolId: 'party',       emoji: '🎉', name: 'Party' },
  { symbolId: 'fireworks',   emoji: '🎆', name: 'Fireworks' },
  { symbolId: 'candle',      emoji: '🕯', name: 'Candle' },
  { symbolId: 'lantern',     emoji: '🏮', name: 'Lantern' },
  // Fantasy / characters
  { symbolId: 'ghost',       emoji: '👻', name: 'Ghost' },
  { symbolId: 'skull',       emoji: '💀', name: 'Skull' },
  { symbolId: 'robot',       emoji: '🤖', name: 'Robot' },
  { symbolId: 'clown',       emoji: '🤡', name: 'Clown' },
  { symbolId: 'pumpkin',     emoji: '🎃', name: 'Pumpkin' },
  { symbolId: 'santa',       emoji: '🎅', name: 'Santa' },
  { symbolId: 'wizard',      emoji: '🧙', name: 'Wizard' },
  { symbolId: 'dragon',      emoji: '🐉', name: 'Dragon' },
  { symbolId: 'angel',       emoji: '😇', name: 'Angel' },
  { symbolId: 'devil',       emoji: '😈', name: 'Devil' },
  { symbolId: 'ninja',       emoji: '🥷', name: 'Ninja' },
  { symbolId: 'superhero',   emoji: '🦸', name: 'Superhero' },
  // Places / buildings
  { symbolId: 'house',       emoji: '🏠', name: 'House' },
  { symbolId: 'castle',      emoji: '🏰', name: 'Castle' },
  { symbolId: 'mountain',    emoji: '⛰', name: 'Mountain' },
  { symbolId: 'volcano',     emoji: '🌋', name: 'Volcano' },
  { symbolId: 'beach',       emoji: '🏖', name: 'Beach' },
  { symbolId: 'island',      emoji: '🏝', name: 'Island' },
  { symbolId: 'tent',        emoji: '⛺', name: 'Tent' },
  { symbolId: 'bridge',      emoji: '🌉', name: 'Bridge' },
  { symbolId: 'ferriswheel', emoji: '🎡', name: 'Ferris Wheel' },
  { symbolId: 'carousel',    emoji: '🎠', name: 'Carousel' },
  // Misc
  { symbolId: 'heart',       emoji: '❤️', name: 'Heart' },
  { symbolId: 'dizzystar',   emoji: '💫', name: 'Dizzy Star' },
  { symbolId: 'crystalball', emoji: '🔮', name: 'Crystal Ball' },
  { symbolId: 'magicwand',   emoji: '🪄', name: 'Magic Wand' },
  { symbolId: 'dice',        emoji: '🎲', name: 'Dice' },
  { symbolId: 'chess',       emoji: '♟', name: 'Chess' },
  { symbolId: 'joystick',    emoji: '🕹', name: 'Joystick' },
  { symbolId: 'gamepad',     emoji: '🎮', name: 'Game Controller' },
  { symbolId: 'jigsaw',      emoji: '🧩', name: 'Jigsaw' },
  { symbolId: 'yoyo',        emoji: '🪀', name: 'Yo-yo' },
  { symbolId: 'frisbee',     emoji: '🥏', name: 'Frisbee' },
  { symbolId: 'abacus',      emoji: '🧮', name: 'Abacus' },
];

export interface LevelDeck {
  cards: MemoryCard[];
  targetQueue: string[];
}

export function buildLevelDeck(level: number): LevelDeck {
  const config = LEVEL_CONFIGS[level - 1] ?? LEVEL_CONFIGS[0];
  const shuffled = [...MEMORY_POOL].sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, config.cardCount);

  const cards: MemoryCard[] = selected.map((item, idx) => ({
    id: idx,
    symbolId: item.symbolId,
    artStyleId: ART_STYLES[idx % ART_STYLES.length].id,
    emoji: item.emoji,
    name: item.name,
  }));

  const targetQueue = [...cards]
    .sort(() => Math.random() - 0.5)
    .slice(0, config.roundCount)
    .map((c) => c.symbolId);

  return { cards, targetQueue };
}

export const getMemoryItemById = (symbolId: string) =>
  MEMORY_POOL.find((item) => item.symbolId === symbolId) ?? MEMORY_POOL[0];
